"""
This file holds the string definitions for SQL commands which are needed in the
database manager class.
"""

CREATE_SUPPLIER_TABLE = """CREATE TABLE IF NOT EXISTS SUPPLIER
(
SupplierID INTEGER NOT NULL PRIMARY KEY,
Name VARCHAR(100) NOT NULL,
Phone VARCHAR(11),
Email VARCHAR(254)
);"""

CREATE_STOCK_TABLE = """CREATE TABLE IF NOT EXISTS STOCK
(
StockID INTEGER NOT NULL PRIMARY KEY,
Name VARCHAR(100) NOT NULL,
Amount INTEGER NOT NULL,
Price INTEGER NOT NULL,
Website TEXT,
SupplierID INTEGER,
FOREIGN KEY(SupplierID) REFERENCES SUPPLIER(SupplierID)
);"""

CREATE_BOOKED_STOCK_TABLE = """CREATE TABLE IF NOT EXISTS BOOKED_STOCK
(
BookingID INTEGER,
StockID INTEGER,
Amount INTEGER NOT NULL,
FOREIGN KEY(StockID) REFERENCES STOCK(StockID),
FOREIGN KEY(BookingID) REFERENCES BOOKINGS(BookingID)
);"""

CREATE_BOOKINGS_TABLE = """CREATE TABLE IF NOT EXISTS BOOKINGS
(
BookingID INTEGER NOT NULL PRIMARY KEY,
UserID INTEGER,
LabID INTEGER,
Date DATE NOT NULL,
Time TIME NOT NULL,
FOREIGN KEY(UserID) REFERENCES USERS(UserID),
FOREIGN KEY(LabID) REFERENCES USERS(UserID)
);"""

CREATE_USERS_TABLE = """CREATE TABLE IF NOT EXISTS USERS
(
UserID INTEGER NOT NULL PRIMARY KEY,
Name VARCHAR(100) NOT NULL,
Email VARCHAR(254) NOT NULL,
PasswordHash VARCHAR(255) NOT NULL,
Priority INTEGER NOT NULL
);"""

CREATE_LABS_TABLE = """CREATE TABLE IF NOT EXISTS LABS
(
LabID INTEGER PRIMARY KEY,
Name VARCHAR(100) NOT NULL,
Location TEXT
);"""

CREATE_INSTITUTION_TABLE = """CREATE TABLE IF NOT EXISTS INSTITUTION
(
PasswordHash CHAR(128) PRIMARY KEY
);"""

INSERT_DEFAULT_PASSWORD = """INSERT INTO INSTITUTION VALUES("827ccb0eea8a706c4c34a16891f84e7b")"""
