# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AddStockWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddStock(object):
    def setupUi(self, AddStock):
        AddStock.setObjectName("AddStock")
        AddStock.resize(524, 316)
        AddStock.setStyleSheet("/*General Styling*/\n"
"\n"
"* {\n"
"    font: 10pt \"Roboto\";\n"
"    font-size: 14px;\n"
"    line-height: 20px;\n"
"    background-color: #0388fc;\n"
"    color: #000000;\n"
"}\n"
"\n"
"/* Text box styling*/\n"
"\n"
"QTextBrowser {\n"
"    border: none;\n"
"    padding-left:10px; \n"
"    padding-top:10px;\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"/* Line edit styling */\n"
"QLineEdit {\n"
"    border: 10px;\n"
"    border-color: #fc7303;\n"
"    padding-left:10px; \n"
"    background-color: #FFFFFF;\n"
"    border-radius: 20px;\n"
"}\n"
"QLineEdit::hover {\n"
"    border: 5px solid;\n"
"    border-color: #fc7303;\n"
"}\n"
"\n"
"/* Label styling */\n"
"QLabel {\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    padding-left:10px; \n"
"    background-color: #FFFFFF;\n"
"    color: #fc7303;\n"
"    font-size: 30px;\n"
"}\n"
"\n"
"/* Scroll bar */\n"
"QScrollBar\n"
"{\n"
"    width:10px;\n"
"    border: none;\n"
"    background: #0388fc;\n"
"}\n"
"QScrollBar::add-page, QScrollBar::sub-page \n"
"{\n"
"    background: #0388fc;\n"
"}\n"
"QScrollBar::add-line, QScrollBar::sub-line \n"
"{\n"
"    background: #0388fc;\n"
"}\n"
"QScrollBar::handle\n"
"{\n"
"    background-color: #fc7303;\n"
"    min-height: 30px;\n"
"    border-radius: 5px;\n"
"    border:none;\n"
"}\n"
"QScrollBar::up-arrow\n"
"{\n"
"    background: none;\n"
"}\n"
"QScrollBar::down-arrow\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"/* Button styling */\n"
"QPushButton {\n"
"    background-color: #ffffff;\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton::hover {\n"
"    border: 5px solid;\n"
"    border-color: #fc7303;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #fc7303;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Remove border */\n"
"QScrollArea {\n"
"    border:none;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(AddStock)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.website = QtWidgets.QLineEdit(self.centralwidget)
        self.website.setMinimumSize(QtCore.QSize(0, 50))
        self.website.setObjectName("website")
        self.gridLayout.addWidget(self.website, 4, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setMinimumSize(QtCore.QSize(0, 50))
        self.name.setText("")
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 0, 1, 2)
        self.amount = QtWidgets.QLineEdit(self.centralwidget)
        self.amount.setMinimumSize(QtCore.QSize(0, 50))
        self.amount.setObjectName("amount")
        self.gridLayout.addWidget(self.amount, 2, 0, 1, 1)
        self.phone = QtWidgets.QLineEdit(self.centralwidget)
        self.phone.setMinimumSize(QtCore.QSize(0, 50))
        self.phone.setObjectName("phone")
        self.gridLayout.addWidget(self.phone, 3, 1, 1, 1)
        self.price = QtWidgets.QLineEdit(self.centralwidget)
        self.price.setMinimumSize(QtCore.QSize(0, 50))
        self.price.setObjectName("price")
        self.gridLayout.addWidget(self.price, 3, 0, 1, 1)
        self.email = QtWidgets.QLineEdit(self.centralwidget)
        self.email.setMinimumSize(QtCore.QSize(0, 50))
        self.email.setObjectName("email")
        self.gridLayout.addWidget(self.email, 4, 1, 1, 1)
        self.supplier_name = QtWidgets.QLineEdit(self.centralwidget)
        self.supplier_name.setMinimumSize(QtCore.QSize(0, 50))
        self.supplier_name.setObjectName("supplier_name")
        self.gridLayout.addWidget(self.supplier_name, 2, 1, 1, 1)
        self.addstock = QtWidgets.QPushButton(self.centralwidget)
        self.addstock.setMinimumSize(QtCore.QSize(0, 50))
        self.addstock.setObjectName("addstock")
        self.gridLayout.addWidget(self.addstock, 5, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        AddStock.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AddStock)
        self.statusbar.setObjectName("statusbar")
        AddStock.setStatusBar(self.statusbar)

        self.retranslateUi(AddStock)
        QtCore.QMetaObject.connectSlotsByName(AddStock)

    def retranslateUi(self, AddStock):
        _translate = QtCore.QCoreApplication.translate
        AddStock.setWindowTitle(_translate("AddStock", "Add stock"))
        self.website.setPlaceholderText(_translate("AddStock", "Enter Website"))
        self.name.setPlaceholderText(_translate("AddStock", "Enter Name"))
        self.amount.setPlaceholderText(_translate("AddStock", "Enter Amount"))
        self.phone.setPlaceholderText(_translate("AddStock", "Enter Supplier Phone"))
        self.price.setPlaceholderText(_translate("AddStock", "Enter Price"))
        self.email.setPlaceholderText(_translate("AddStock", "Enter Supplier Email"))
        self.supplier_name.setPlaceholderText(_translate("AddStock", "Enter Supplier Name"))
        self.addstock.setText(_translate("AddStock", "Add Stock Item"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddStock = QtWidgets.QMainWindow()
    ui = Ui_AddStock()
    ui.setupUi(AddStock)
    AddStock.show()
    sys.exit(app.exec_())
