# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\BookingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BookingWindow(object):
    def setupUi(self, BookingWindow):
        BookingWindow.setObjectName("BookingWindow")
        BookingWindow.resize(854, 593)
        BookingWindow.setStyleSheet("/*General Styling*/\n"
"\n"
"* {\n"
"    font: 10pt \"Roboto\";\n"
"    font-size: 14px;\n"
"    line-height: 20px;\n"
"    background-color: #0388fc;\n"
"    color: #000000;\n"
"}\n"
"\n"
"/* Text box styling*/\n"
"\n"
"QTextBrowser {\n"
"    border: none;\n"
"    padding-left:10px; \n"
"    padding-top:10px;\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"/* Line edit styling */\n"
"QLineEdit {\n"
"    border: 10px;\n"
"    border-color: #fc7303;\n"
"    padding-left:10px; \n"
"    background-color: #FFFFFF;\n"
"    border-radius: 20px;\n"
"}\n"
"QLineEdit::hover {\n"
"    border: 5px solid;\n"
"    border-color: #fc7303;\n"
"}\n"
"\n"
"/* Label styling */\n"
"QLabel {\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    padding-left:10px; \n"
"    background-color: #FFFFFF;\n"
"    color: #fc7303;\n"
"    font-size: 30px;\n"
"}\n"
"\n"
"/* Scroll bar */\n"
"QScrollBar\n"
"{\n"
"    width: 20px;\n"
"    border:none;\n"
"    border-radius: 10px;\n"
"    background: #ffffff;\n"
"}\n"
"QScrollBar::add-page, QScrollBar::sub-page \n"
"{\n"
"    background: #ffffff;\n"
"}\n"
"QScrollBar::add-line, QScrollBar::sub-line \n"
"{\n"
"    background: #ffffff;\n"
"}\n"
"QScrollBar::handle\n"
"{\n"
"    background-color: #fc7303;\n"
"    min-height: 30px;\n"
"    border-radius: 10px;\n"
"    border:none;\n"
"}\n"
"QScrollBar::up-arrow\n"
"{\n"
"    background: none;\n"
"}\n"
"QScrollBar::down-arrow\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"/* Button styling */\n"
"QPushButton {\n"
"    background-color: #ffffff;\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton::hover {\n"
"    border: 5px solid;\n"
"    border-color: #fc7303;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #fc7303;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Combo Box Styling */\n"
"QComboBox {\n"
"    background-color: #ffffff;\n"
"    border: 5px solid #ffffff;\n"
"    border-radius: 20px;\n"
"    padding-left: 20px;\n"
"}\n"
"QComboBox:hover {\n"
"    border: 5px solid #fc7303;\n"
"}\n"
"QComboBox:editable {\n"
"    background: #ffffff;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border: none;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: #000000;\n"
"    background-color: #ffffff;\n"
"    border: 5px solid #fc7303;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(BookingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.notification = QtWidgets.QLabel(self.centralwidget)
        self.notification.setMinimumSize(QtCore.QSize(0, 50))
        self.notification.setText("")
        self.notification.setObjectName("notification")
        self.gridLayout.addWidget(self.notification, 1, 0, 1, 3)
        self.stock_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.stock_amount.setMinimumSize(QtCore.QSize(0, 50))
        self.stock_amount.setObjectName("stock_amount")
        self.gridLayout.addWidget(self.stock_amount, 6, 0, 1, 1)
        self.booking_info = QtWidgets.QTextBrowser(self.centralwidget)
        self.booking_info.setObjectName("booking_info")
        self.gridLayout.addWidget(self.booking_info, 2, 1, 12, 2)
        self.confirm_booking = QtWidgets.QPushButton(self.centralwidget)
        self.confirm_booking.setMinimumSize(QtCore.QSize(0, 50))
        self.confirm_booking.setObjectName("confirm_booking")
        self.gridLayout.addWidget(self.confirm_booking, 12, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 1)
        self.add_stock = QtWidgets.QPushButton(self.centralwidget)
        self.add_stock.setMinimumSize(QtCore.QSize(0, 50))
        self.add_stock.setObjectName("add_stock")
        self.gridLayout.addWidget(self.add_stock, 7, 0, 1, 1)
        self.date = QtWidgets.QComboBox(self.centralwidget)
        self.date.setMinimumSize(QtCore.QSize(0, 50))
        self.date.setObjectName("date")
        self.gridLayout.addWidget(self.date, 9, 0, 1, 1)
        self.stock = QtWidgets.QComboBox(self.centralwidget)
        self.stock.setMinimumSize(QtCore.QSize(0, 50))
        self.stock.setObjectName("stock")
        self.gridLayout.addWidget(self.stock, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.time = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time.sizePolicy().hasHeightForWidth())
        self.time.setSizePolicy(sizePolicy)
        self.time.setMinimumSize(QtCore.QSize(0, 50))
        self.time.setObjectName("time")
        self.gridLayout.addWidget(self.time, 10, 0, 1, 1)
        self.lab = QtWidgets.QComboBox(self.centralwidget)
        self.lab.setMinimumSize(QtCore.QSize(0, 50))
        self.lab.setObjectName("lab")
        self.gridLayout.addWidget(self.lab, 11, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        BookingWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(BookingWindow)
        self.statusbar.setObjectName("statusbar")
        BookingWindow.setStatusBar(self.statusbar)

        self.retranslateUi(BookingWindow)
        QtCore.QMetaObject.connectSlotsByName(BookingWindow)

    def retranslateUi(self, BookingWindow):
        _translate = QtCore.QCoreApplication.translate
        BookingWindow.setWindowTitle(_translate("BookingWindow", "Laboratory Booking"))
        self.stock_amount.setPlaceholderText(_translate("BookingWindow", "Stock amount"))
        self.confirm_booking.setText(_translate("BookingWindow", "Confirm Booking"))
        self.add_stock.setText(_translate("BookingWindow", "Add Stock"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BookingWindow = QtWidgets.QMainWindow()
    ui = Ui_BookingWindow()
    ui.setupUi(BookingWindow)
    BookingWindow.show()
    sys.exit(app.exec_())
