# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(872, 528)
        MainWindow.setStyleSheet("* {\n"
"    background-color: #ffffff;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("* {\n"
"    background-color: #ffffff;\n"
"    border-radius: 20px;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 850, 384))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.time_table = QtWidgets.QGridLayout()
        self.time_table.setObjectName("time_table")
        self.gridLayout_4.addLayout(self.time_table, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_6.addWidget(self.scrollArea, 1, 0, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.horizontalFrame = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame.setStyleSheet("*{\n"
"    background-color: #0388fc;\n"
"}\n"
"\n"
"/* Button styling */\n"
"QPushButton {\n"
"    color: #ffffff;\n"
"    background-color: #0388fc;\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton::hover {\n"
"    border: 5px solid;\n"
"    border-color: #fc7303;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: #fc7303;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Combo Box Styling */\n"
"QComboBox {\n"
"    color: #ffffff;\n"
"    background-color: #0388fc;\n"
"    border: 5px solid #0388fc;\n"
"    padding-left: 20px;\n"
"}\n"
"QComboBox:hover {\n"
"    border-top: 5px solid #fc7303;\n"
"    border-left: 5px solid #fc7303;\n"
"    border-right: 5px solid #fc7303;\n"
"    border-radius: 0px 0px 0px 0px;\n"
"}\n"
"QComboBox:editable {\n"
"    background: #0388fc;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-left: none;\n"
"    color: #00f0c3;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    content: \"V\";\n"
"    color: #ffffff;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: #ffffff;\n"
"    background-color: #0388fc;\n"
"    border-bottom: 5px solid #fc7303;\n"
"    border-left: 5px solid #fc7303;\n"
"    border-right: 5px solid #fc7303;\n"
"    border-radius: 0px 0px 20px 20px;\n"
"    padding: 10px;\n"
"}")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.top_bar = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.top_bar.setContentsMargins(10, 10, 10, 10)
        self.top_bar.setSpacing(10)
        self.top_bar.setObjectName("top_bar")
        self.log_experiment = QtWidgets.QPushButton(self.horizontalFrame)
        self.log_experiment.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.log_experiment.setFont(font)
        self.log_experiment.setObjectName("log_experiment")
        self.top_bar.addWidget(self.log_experiment)
        self.manage_stock = QtWidgets.QPushButton(self.horizontalFrame)
        self.manage_stock.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.manage_stock.setFont(font)
        self.manage_stock.setObjectName("manage_stock")
        self.top_bar.addWidget(self.manage_stock)
        self.date_range = QtWidgets.QComboBox(self.horizontalFrame)
        self.date_range.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.date_range.setFont(font)
        self.date_range.setObjectName("date_range")
        self.date_range.addItem("")
        self.date_range.addItem("")
        self.date_range.addItem("")
        self.top_bar.addWidget(self.date_range)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.top_bar.addItem(spacerItem1)
        self.account = QtWidgets.QPushButton(self.horizontalFrame)
        self.account.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.account.setFont(font)
        self.account.setObjectName("account")
        self.top_bar.addWidget(self.account)
        self.help = QtWidgets.QPushButton(self.horizontalFrame)
        self.help.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.help.setFont(font)
        self.help.setObjectName("help")
        self.top_bar.addWidget(self.help)
        self.gridLayout_2.addWidget(self.horizontalFrame, 0, 0, 1, 1)
        self.gridLayout_2.setRowStretch(1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "A Lab Management System"))
        self.log_experiment.setText(_translate("MainWindow", "Log Experiment"))
        self.manage_stock.setText(_translate("MainWindow", "Manage Stock"))
        self.date_range.setItemText(0, _translate("MainWindow", "20/11/23"))
        self.date_range.setItemText(1, _translate("MainWindow", "27/11/23"))
        self.date_range.setItemText(2, _translate("MainWindow", "03/12/23"))
        self.account.setText(_translate("MainWindow", "Account"))
        self.help.setText(_translate("MainWindow", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
