name: Pylint

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt

    - name: Analysing server_manager.py
      run: |
        pylint ./Server-Side/server_manager.py --disable=W0511

    - name: Analysing database_manager.py
      run: |
        pylint ./Server-Side/database_manager.py --disable=W0511

    - name: Analysing connection_manager.py
      run: |
        pylint ./Server-Side/connection_manager.py --disable=W0511

    - name: Analysing email_manager.py
      run: |
        pylint ./Server-Side/email_manager.py --disable=W0511

    - name: Analysing server-side.py
      run: |
        pylint ./Server-Side/main.py --disable=W0511

    - name: Analysing graph_manager.py
      run: |
        pylint ./Client-Side/graph_manager.py --disable=W0511

    - name: Analysing connection_manager.py
      run: |
        pylint ./Client-Side/connection_manager.py --disable=W0511

    - name: Analysing booking_manager.py
      run: |
        pylint ./Client-Side/booking_manager.py --disable=W0511

    - name: Analysing account_manager.py
      run: |
        pylint ./Client-Side/account_manager.py --disable=W0511

    - name: Analysing graph_manager.py
      run: |
        pylint ./Client-Side/graph_manager.py --disable=W0511

    - name: Analysing stock_manager.py
      run: |
        pylint ./Client-Side/stock_manager.py --disable=W0511

    - name: Analysing main_window.py
      run: |
        pylint ./Client-Side/main_window.py --disable=W0511

    - name: Analysing client-side
      run: |
        pylint ./Client-Side/main.py --disable=W0511